"""Admin analytics report generation (PDF + Excel)."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def generate_admin_pdf(analytics_data: dict[str, Any], output_path: str) -> None:
    """Generate monthly TEAM progress PDF summary."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    summary = analytics_data.get("summary", {})
    women = analytics_data.get("women_mse", {})
    bottleneck = analytics_data.get("bottleneck", {})
    snp_summary = analytics_data.get("snp_performance_summary", {})

    c = canvas.Canvas(str(path), pagesize=A4)
    width, height = A4
    y = height - 30

    c.setFont("Helvetica-Bold", 18)
    c.drawString(30, y, "VyaparSetu Admin Progress Report")
    y -= 18
    c.setFont("Helvetica", 10)
    c.drawString(30, y, "Monthly TEAM progress across onboarding funnel and inclusion goals")
    y -= 26

    c.setFont("Helvetica-Bold", 12)
    c.drawString(30, y, "Funnel Summary")
    y -= 14
    c.setFont("Helvetica", 10)
    for key in ["registered", "catalog_created", "snp_matched", "live", "first_order"]:
        value = summary.get(key, 0)
        c.drawString(30, y, f"{key}: {value}")
        y -= 12

    y -= 8
    c.setFont("Helvetica-Bold", 12)
    c.drawString(30, y, "Women MSE Tracking")
    y -= 14
    c.setFont("Helvetica", 10)
    c.drawString(30, y, f"Women-owned share: {women.get('women_percentage', 0):.2f}%")
    y -= 12
    c.drawString(30, y, f"Target (TEAM): {women.get('target_percentage', 50):.2f}%")
    y -= 18

    c.setFont("Helvetica-Bold", 12)
    c.drawString(30, y, "Bottleneck Analysis")
    y -= 14
    c.setFont("Helvetica", 10)
    c.drawString(30, y, f"Worst stage: {bottleneck.get('worst_conversion_stage', 'N/A')}")
    y -= 12
    c.drawString(30, y, f"Rate: {bottleneck.get('rate', 0):.4f}")
    y -= 12
    c.drawString(30, y, f"Suggested action: {bottleneck.get('suggested_action', 'N/A')[:100]}")
    y -= 18

    c.setFont("Helvetica-Bold", 12)
    c.drawString(30, y, "SNP Performance Snapshot")
    y -= 14
    c.setFont("Helvetica", 10)
    c.drawString(30, y, f"Total SNP profiles: {snp_summary.get('total_snps', 0)}")
    y -= 12
    c.drawString(30, y, f"Avg seller success rate: {snp_summary.get('avg_success_rate', 0):.3f}")
    y -= 12
    c.drawString(30, y, f"Avg activation days: {snp_summary.get('avg_activation_days', 0):.2f}")

    # Chart placeholders (for print-ready report narrative).
    y -= 30
    c.setFont("Helvetica-Bold", 11)
    c.drawString(30, y, "Figure placeholders:")
    y -= 14
    c.setFont("Helvetica", 10)
    c.drawString(30, y, "- Funnel conversion chart")
    y -= 12
    c.drawString(30, y, "- State-wise onboarding heatmap")
    y -= 12
    c.drawString(30, y, "- Women MSE gauge and category distribution")
    y -= 12
    c.drawString(30, y, "- SNP performance comparison")

    c.setFont("Helvetica", 8)
    c.drawString(30, 30, "Generated by VyaparSetu reporting module")
    c.save()


def export_admin_excel(analytics_data: dict[str, Any], output_path: str) -> None:
    """Export admin analytics to multi-sheet Excel workbook."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    summary_df = pd.DataFrame([analytics_data.get("summary", {})])
    state_wise_df = _to_df(analytics_data.get("state_wise", []))
    category_wise_df = _to_df(analytics_data.get("category_wise", []))
    women_df = pd.DataFrame([analytics_data.get("women_mse", {})])
    snp_df = _to_df(analytics_data.get("snp_performance", []))
    monthly_df = _to_df(analytics_data.get("monthly_trends", []))

    with pd.ExcelWriter(path, engine="openpyxl") as writer:
        summary_df.to_excel(writer, index=False, sheet_name="Summary")
        state_wise_df.to_excel(writer, index=False, sheet_name="State-wise")
        category_wise_df.to_excel(writer, index=False, sheet_name="Category-wise")
        women_df.to_excel(writer, index=False, sheet_name="Women MSE")
        snp_df.to_excel(writer, index=False, sheet_name="SNP Performance")
        monthly_df.to_excel(writer, index=False, sheet_name="Monthly Trends")


def _to_df(rows: Any) -> pd.DataFrame:
    if isinstance(rows, pd.DataFrame):
        return rows
    if isinstance(rows, list):
        return pd.DataFrame(rows)
    return pd.DataFrame()

