"""Registration report PDF generation."""

from __future__ import annotations

import tempfile
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from src.common.models import TEAMRegistration

try:
    import qrcode
except Exception:  # pragma: no cover - optional dependency
    qrcode = None


def generate_registration_pdf(registration: TEAMRegistration, output_path: str) -> None:
    """Generate registration summary PDF with TEAM portal QR placeholder."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    c = canvas.Canvas(str(path), pagesize=A4)
    width, height = A4
    profile = registration.mse_profile

    y = height - 30
    c.setFont("Helvetica-Bold", 18)
    c.drawString(30, y, "VyaparSetu Registration Report")

    y -= 18
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.grey)
    c.drawString(30, y, "TEAM Initiative onboarding summary")
    c.setFillColor(colors.black)

    y -= 24
    c.setFont("Helvetica-Bold", 12)
    c.drawString(30, y, "MSE Details")
    c.setFont("Helvetica", 10)
    y -= 14
    lines = [
        f"Registration ID: {registration.registration_id}",
        f"Status: {registration.registration_status}",
        f"Udyam Number: {profile.udyam_number}",
        f"Enterprise: {profile.enterprise_name}",
        f"Owner: {profile.owner_name} ({profile.owner_gender})",
        f"Location: {profile.district}, {profile.state}",
        f"Primary Categories: {', '.join(registration.product_categories)}",
        f"Selected SNP ID: {registration.preferred_snp_id or 'Not selected'}",
        f"Language: {registration.language}",
        f"Submitted At: {registration.submitted_at.isoformat() if registration.submitted_at else 'N/A'}",
    ]
    for line in lines:
        c.drawString(30, y, line[:120])
        y -= 13

    y -= 8
    c.setFont("Helvetica-Bold", 12)
    c.drawString(30, y, "Catalog Summary")
    c.setFont("Helvetica", 10)
    y -= 14
    c.drawString(30, y, f"Total Catalog Items: {len(registration.catalog_items)}")
    y -= 13

    for idx, item in enumerate(registration.catalog_items[:10], start=1):
        c.drawString(
            30,
            y,
            f"{idx}. {item.product_name_en[:45]} | {item.category_l1}>{item.category_l2} | INR {item.price_selling:.2f}",
        )
        y -= 12
        if y < 120:
            c.showPage()
            y = height - 30
            c.setFont("Helvetica", 10)

    # QR block for TEAM portal handoff with graceful fallback.
    box_size = 35 * mm
    x0 = width - box_size - 30
    y0 = 30
    qr_url = f"https://team.msmemart.com/verify/{profile.udyam_number}"
    qr_drawn = False
    temp_qr_path: Path | None = None

    if qrcode is not None:
        try:
            qr = qrcode.QRCode(version=1, box_size=8, border=2)
            qr.add_data(qr_url)
            qr.make(fit=True)
            image = qr.make_image(fill_color="black", back_color="white")
            with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as handle:
                temp_qr_path = Path(handle.name)
            image.save(temp_qr_path)
            c.drawImage(str(temp_qr_path), x0, y0, width=box_size, height=box_size, preserveAspectRatio=True, mask="auto")
            c.setFont("Helvetica", 7)
            c.drawCentredString(x0 + box_size / 2, y0 - 8, "TEAM verification QR")
            qr_drawn = True
        except Exception:
            qr_drawn = False
        finally:
            if temp_qr_path is not None and temp_qr_path.exists():
                try:
                    temp_qr_path.unlink()
                except OSError:
                    pass

    if not qr_drawn:
        c.setStrokeColor(colors.black)
        c.rect(x0, y0, box_size, box_size, stroke=1, fill=0)
        c.setFont("Helvetica", 8)
        c.drawCentredString(x0 + box_size / 2, y0 + box_size / 2, "TEAM QR")
        c.drawCentredString(x0 + box_size / 2, y0 + box_size / 2 - 10, "Placeholder")

    c.setFont("Helvetica", 8)
    c.drawString(30, 30, "Generated by VyaparSetu reporting module")
    c.save()

